### ISSUE TITLE
Missing reference to PortfolioBuilder() ?

### ISSUE THREAD

**Issue by yangar** [salmonthinlion/Trady#1]
Thank you for this project !!!

// Create portfolio instance by using PortfolioBuilder
var portfolio = new PortfolioBuilder()
    .Add(equity, 10)
    .Add(equity2, 30)
    .Buy(buyRule)
    .Sell(sellRule)
    .Build();

I can't find any reference to PortfolioBuilder() in the project, is it missing ?

**Comment by salmonthinlion** [comment]
Hi @yangar,

It seems I haven't made an update on the README.md, the new syntax for portfolio creation is now:

var portfolio = new Portfolio().Add(equity, 10).Buy(buyRule).Sell(sellRule);
var result = await portfolio.RunBacktestAsync();

Thanks for pointing out the issue.

Karl
